apiVersion: v1
kind: Secret
metadata:
  name: mail-secrets
  namespace: microservices-shop
type: Opaque
stringData:
  mail-host: sandbox.smtp.mailtrap.io
  mail-port: "2525"
  mail-username: changeme
  mail-password: changeme
