apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: microservices-shop
type: Opaque
stringData:
  root-password: mysql
  keycloak-password: password
  keycloak-root-password: root
