apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: microservices-shop
data:
  SPRING_PROFILES_ACTIVE: docker
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak:8080/realms/Spring-microservices-security-realm"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
