apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  namespace: microservices-shop
data:
  SPRING_PROFILES_ACTIVE: docker
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-inventory:3306/inventory_service"
  SPRING_DATASOURCE_USERNAME: root
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
