apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: microservices-shop
data:
  SPRING_PROFILES_ACTIVE: docker
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "broker:29092"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
