apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-mysql
  namespace: microservices-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-mysql
  template:
    metadata:
      labels:
        app: keycloak-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.3.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: keycloak-root-password
            - name: MYSQL_DATABASE
              value: "keycloak"
            - name: MYSQL_USER
              value: "keycloak"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: keycloak-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests: { memory: "256Mi", cpu: "250m" }
            limits: { memory: "512Mi", cpu: "500m" }
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: keycloak-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-mysql
  namespace: microservices-shop
spec:
  selector:
    app: keycloak-mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-mysql-pvc
  namespace: microservices-shop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
