apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: microservices-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.1
          args: ["start-dev", "--import-realm"]
          ports:
            - containerPort: 8080
          env:
            - name: DB_VENDOR
              value: "MYSQL"
            - name: DB_ADDR
              value: "keycloak-mysql"
            - name: DB_DATABASE
              value: "keycloak"
            - name: DB_USER
              value: "keycloak"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: keycloak-password
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: admin-user
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: admin-password
          resources:
            requests: { memory: "512Mi", cpu: "500m" }
            limits: { memory: "1Gi", cpu: "1000m" }
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: microservices-shop
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
