apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: microservices-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.5.0
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "schema-registry"
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "broker:29092"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://schema-registry:8081"
          resources:
            requests: { memory: "256Mi", cpu: "250m" }
            limits: { memory: "512Mi", cpu: "500m" }
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: microservices-shop
spec:
  selector:
    app: schema-registry
  ports:
    - port: 8081
      targetPort: 8081
