spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/Spring-microservices-security-realm/protocol/openid-connect/certs
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
product.service.url=http://product-service:8080
order.service.url=http://order-service:8081
inventory.service.url=http://inventory-service:8082
